### ISSUE TITLE
Failed to call CEconItemSchema_GetAttributeDefinitionByName

### ISSUE THREAD

**Issue by ED-E** [akowald/StopThatTank#11]
As one of my moderator reported: "Whenever someone becomes a giant, they are extremely fast and have their weapons acting similarly to the stock ones. "
Since a few weeks i seem to get spammed with this in the console, which results in odd Giants behaviour, all of the extensions/gamedata and plugins are up to date.

L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "move speed bonus" is not valid!
L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "override footstep sound set" is not valid!
L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "cancel falling damage" is not valid!
L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "damage force increase" is not valid!
L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "self dmg push force increased" is not valid!
L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "move speed bonus" is not valid!
L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "cancel falling damage" is not valid!
L 07/21/2018 - 16:19:30: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:30: [TANK] Attribute name "damage force increase" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "clip size upgrade atomic" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "faster reload rate" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "projectile spread angle penalty" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "crit mod disabled" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "damage penalty" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "ubercharge rate bonus" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "overheal bonus" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "uber duration bonus" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "deploy time decreased" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "crit mod disabled" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "crit mod disabled" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "clip size upgrade atomic" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "damage penalty" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "projectile spread angle penalty" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "faster reload rate" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "fire rate bonus" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "can overload" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "rocket jump damage reduction" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "maxammo primary increased" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "Blast radius decreased" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "damage bonus" is not valid!
L 07/21/2018 - 16:19:31: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:19:31: [TANK] Attribute name "fire rate penalty" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "move speed bonus" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "damage force reduction" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "airblast vulnerability multiplier" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "override footstep sound set" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "cancel falling damage" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "special taunt" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "cannot pick up intelligence" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "cannot be backstabbed" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "SET BONUS: dmg from sentry reduced" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "no double jump" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "cannot pick up buildings" is not valid!
L 07/21/2018 - 16:20:06: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:06: [TANK] Attribute name "increased jump height from weapon" is not valid!
L 07/21/2018 - 16:20:14: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:14: [TANK] Attribute name "562272216" is not valid!
L 07/21/2018 - 16:20:14: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:14: [TANK] Attribute name "562272216" is not valid!
L 07/21/2018 - 16:20:14: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:14: [TANK] Attribute name "562272216" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "move speed bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "cancel falling damage" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "damage force increase" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "move speed bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "override footstep sound set" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "cancel falling damage" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "damage force increase" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "bullets per shot bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "fire rate bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "deploy time decreased" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "melee attack rate bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "crit mod disabled" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "clip size upgrade atomic" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "faster reload rate" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "projectile spread angle penalty" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "crit mod disabled" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "damage penalty" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "ubercharge rate bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "overheal bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "uber duration bonus" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "deploy time decreased" is not valid!
L 07/21/2018 - 16:20:16: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:16: [TANK] Attribute name "crit mod disabled" is not valid!
L 07/21/2018 - 16:20:17: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:17: [TANK] Attribute name "562272064" is not valid!
L 07/21/2018 - 16:20:17: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:17: [TANK] Attribute name "562272064" is not valid!
L 07/21/2018 - 16:20:17: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:17: [TANK] Attribute name "562272064" is not valid!
L 07/21/2018 - 16:20:17: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:17: [TANK] Attribute name "562272064" is not valid!
L 07/21/2018 - 16:20:17: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:17: [TANK] Attribute name "562272064" is not valid!
L 07/21/2018 - 16:20:17: [TANK]  > Failed to call CEconItemSchema_GetAttributeDefinitionByName.
L 07/21/2018 - 16:20:17: [TANK] Attribute name "562272064" is not valid!

**Comment by akowald** [comment]
Thanks for catching this! You can just copy the updated tank.txt file and restart. I've updated it in the release as well.
