### ISSUE TITLE
Stop That Tank extension is not working on Sourcemod1.10

### ISSUE THREAD

**Issue by doroemon** [akowald/StopThatTank#15]
L 04/17/2020 - 20:40:00: [TANK] Unable to retrieve interface: BINTOOLS!
[SM] Plugin tank.smx failed to load: Required extension "Stop that Tank!" file("tank.ext") not running.

**Comment by akowald** [comment]
I'll get this fixed later today along with those other pull requests, thanks!

**Comment by doroemon** [comment]
Thanks for keeping this game mode alive! :D

**Comment by akowald** [comment]
Should be working now, ended up being more work than I bargained for 😅 Let me know if you run into anything.
