### ISSUE TITLE
Bots dumber than ever

### ISSUE THREAD

**Issue by NickCloudAT** [akowald/StopThatTank#17]
Hey,

I really love this gamemode.. Unfortunately this gamemode seems to mess with the default TF2-Bots AI.. 
For example on pl_upward if blu bots spawn in theirs second spawn (in that cave) they just WANT to walk through the corner of the room and will never leave it again :/ (https://prnt.sc/s5qthq).
This also somewhat happens on other maps. pl_badwater (Red bots will try to go trough their door, even tough it closed after 2 point is capped).

Is there anyway to get this fixed :/?

**Comment by Kenzzer** [comment]
This is not caused by the gamemode. This behavior will also occur without StopThatTank enabled.
To fix this issue you will have to edit the nav file of this map, and apply proper nav attributes around spawn doors. Google it, there are many tutorials on how to do tf2 nav edition around.

**Comment by TheNickSkater** [comment]
> This is not caused by the gamemode. This behavior will also occur without StopThatTank enabled.
> To fix this issue you will have to edit the nav file of this map, and apply proper nav attributes around spawn doors. Google it, there are many tutorials on how to do tf2 nav edition around.

This is not true. I tested it on a few different maps now.. It ONLY happened to me with STT.

**Comment by TheNickSkater** [comment]
K, after thoroughly testing 6 maps AND even editing the navmesh of the maps to make sure, I'm now 100% sure that STT is causing Bots to perform poorly in some cases etc..

**Comment by Kenzzer** [comment]
Again, STT does not mess in any notable ways with TFBots. The issue you have in your first screenshot also happens on regular upward payload map. That issue cannot be fixed because STT isn't responsible for it. Edit your nav file and you'll be good.

If instead you want STT to support TFBots it's a feature request, not a bug to fix.

**Comment by TheNickSkater** [comment]
> Again, STT does not mess in any notable ways with TFBots. The issue you have in your first screenshot also happens on regular upward payload map. That issue cannot be fixed because STT isn't responsible for it. Edit your nav file and you'll be good.
> 
> If instead you want STT to support TFBots it's a feature request, not a bug to fix.

I can just disagree. THIS DOES NOT HAPPEN ON REGULAR PAYLOAD!! I now tested it 10! times WITH and WITHOUT STT. It still ONLY happens with STT. I tested in on singleplayer AND on an dedicated server.

**Comment by Kenzzer** [comment]
Can you please not scream at me, and try to instead provide more information.

Here's some from me:
https://cdn.discordapp.com/attachments/435269309225369641/704749608579891240/unknown.png
A regular game, stop that tank isn't loaded, and bots stand in their spawn.

**Comment by TheNickSkater** [comment]
> Can you please not scream at me, and try to instead provide more information.
> 
> Here's some from me:
> https://cdn.discordapp.com/attachments/435269309225369641/704749608579891240/unknown.png
> A regular game, stop that tank isn't loaded, and bots stand in their spawn.
> Except for spies and engineers.

Here you have 2 Videos of me playing on a vanilla TF2 Server and on my other server with STT:

Without STT: https://cloud.nickcloud.at/index.php/s/GBXRTmdxGonqAF9
With STT: https://cloud.nickcloud.at/index.php/s/pX5x5KrEfA4Hd7N

Both have the default nav file.

**Comment by Kenzzer** [comment]
Could you try again, with the tank destroyed (giant phase) please?

**Comment by TheNickSkater** [comment]
> Could you try again, with the tank destroyed (giant phase) please?

I did now and noticed 2 different things.. If the tank is getting destroyed BEFORE it reaches the second point, bots will actually leave the spawn normally after I manually reched the point as giant robot.
But on the other hand, if the tank first reaches the point and then gets destroyed, the robots will actually run around in circles in spawn..

**Comment by NickCloudAT** [comment]
closing this after years.. fixed in my private upkeep of stt
