### ISSUE TITLE
Server crashes right after a giant robot has spawned 

### ISSUE THREAD

**Issue by Worco** [akowald/StopThatTank#6]
this happened right after a giant boss has spawned

]pl_upward

Heal Target: ClipSize Data Limit Exceeded: 600 (max 500)
Segmentation Fault

debug.log
----------------------------------------------
CRASH: Sat Jun 11 08:26:29 UTC 2016
Start Line: ./srcds_linux -game tf -maxplayers 26 +map pl_upward -debug
[New LWP 21995]
[New LWP 21996]
[New LWP 21997]
[New LWP 21998]
[New LWP 21999]
[New LWP 22025]
[New LWP 22003]
[New LWP 22021]
[New LWP 22010]
[New LWP 22022]
[New LWP 22001]
[New LWP 22000]
[New LWP 22023]
[New LWP 22002]
[New LWP 22016]
[New LWP 22004]
[New LWP 22012]
[New LWP 22005]
[New LWP 22019]
[New LWP 22006]
[New LWP 22009]
[New LWP 22024]
[New LWP 22007]
[New LWP 22018]
#0  0xf11b55d6 in ?? ()
End of Source crash report
----------------------------------------------

]pl_badwater

srcds_linux: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
*** Error in `./srcds_linux': free(): invalid pointer: 0x1865ffff ***
WatchDog! Server took too long to process (probably infinite loop).
Host_Error: WatchdogHandler called - server exiting.

 SourceMod Version Information:
    SourceMod Version: 1.8.0.5832
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5832)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Jan  7 2016 17:07:48
    Built from: https://github.com/alliedmodders/sourcemod/commit/3dc9c23
    Build ID: 5832:3dc9c23
    http://www.sourcemod.net/

"Stop that Tank!" (1.5.3) by Banshee, linux_lover (abkowald@gmail.com)   //i cloned this from github

Thank you for you time and specially your work.

**Comment by akowald** [comment]
Hey! Unfortunately, I can't pin down the exact cause with this information. An educated guess would be that TF2Items is outdated. Try these things:

* Update to the latest stable sourcemod: [here](http://www.sourcemod.net/downloads.php?branch=stable)
* Make sure you have the latest snapshot of TF2Items: [here](https://builds.limetech.org/?p=tf2items)
* Grab STT from a [release](https://github.com/akowald/StopThatTank/releases)

Hope it helps!

**Comment by Worco** [comment]
updating TF2Items did the trick!

TF2Items (1.6.2): TF2 Item Modifier  -->   TF2Items (1.6.4): TF2 Item Modifier

thanks!
